filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
    fields:
      log_source: openresty
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]
